=== Ezio47/hale/hale/eu.esdihumboldt.hale.io.gml.test/src/data/buek200/target/propertyFile.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:sq="http://www.SoilML.org" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gml="http://www.opengis.net/gml" targetNamespace="http://www.SoilML.org" elementFormDefault="qualified">
	<xsd:import namespace="http://www.isotc211.org/2005/gmd" schemaLocation="http://www.isotc211.org/2005/gmd/metadataEntity.xsd"/>
	<xsd:import namespace="http://www.opengis.net/gml" schemaLocation="http://www.isotc211.org/2005/gml/basicTypes.xsd"/>
	<xsd:import namespace="http://www.w3.org/2001/XMLSchema" schemaLocation="http://www.w3.org/2001/XMLSchema.xsd"/>
	<xsd:complexType name="PropertyFile_Type">
		<xsd:sequence>
			<xsd:element ref="gmd:MD_Metadata"/>
			<xsd:element name="FeatureTypes" type="sq:FeatureTypes_Type"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="SoilML_PropertyFile" type="sq:PropertyFile_Type"/>
	<xsd:complexType name="FeatureTypes_Type">
		<xsd:annotation>
			<xsd:documentation>List of described FeatureTypes.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="FeatureType" type="sq:FeatureType_Type" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="FeatureType_Type">
		<xsd:annotation>
			<xsd:documentation>Any SoilML FeatureType.
        FeatureTypeName shall correspond with SoilML UML model.
        </xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="FeatureTypeName" type="xsd:NCName"/>
			<xsd:element name="Title" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Description" type="xsd:string" minOccurs="0"/>
			<xsd:element name="XSDTypeName" type="xsd:NCName"/>
			<xsd:element name="Property" type="sq:Property_Type" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:ID" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="Property_Type">
		<xsd:annotation>
			<xsd:documentation>Property of FeatureType.
        If the property is introduced by SoilML UML model,
        PropertyName shall correspond with SoilML UML model.
        If the property is an association, RelationShip describes its type.
        If the property refers to a code list, CodeList provides its definition.
        Attribute observable determines if the property is observable or not.
        If the property values were gained by a measurement,
        UnitOfMeasurement enumerates units of measurements used in data file.
        </xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="PropertyName" type="xsd:NCName"/>
			<xsd:element name="Title" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Description" type="xsd:string" minOccurs="0"/>
			<xsd:choice minOccurs="0">
				<xsd:element name="RelationShip" type="sq:RelationShip_Type"/>
				<xsd:element name="CodeList" type="sq:CodeList_Type"/>
				<xsd:element name="UnitOfMeasurement" type="gml:UomIdentifier" maxOccurs="unbounded"/>
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:ID" use="required"/>
		<xsd:attribute name="observable" type="xsd:boolean" use="optional" default="false"/>
	</xsd:complexType>
	<xsd:complexType name="RelationShip_Type">
		<xsd:annotation>
			<xsd:documentation>RelationShip describes type of asociation.
        Type may be one of three values (general association, aggregation, or composition)
        with common UML meaning.
        TargetFeatureTypeRef is a reference to type of target feature. It refers to FeatureTypeName.
        </xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Type">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="association"/>
						<xsd:enumeration value="aggregation"/>
						<xsd:enumeration value="composition"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="TargetFeatureTypeName" type="xsd:Name" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="CodeList_Type">
		<xsd:annotation>
			<xsd:documentation>Definition of a code list.
        If the list classifies a numerical value, the numerical type is defined
        by TypeOfClassifiedNumericalValue. Furthermore, NumericalValuesUnit
        may define its unit.
        </xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="TypeOfClassifiedNumericalValue" type="xsd:Name" minOccurs="0"/>
			<xsd:element name="NumericalValuesUnit" type="gml:UomIdentifier" minOccurs="0"/>
			<xsd:element name="CodeListEntry" type="sq:CodeListEntry_Type" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:ID" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="CodeListEntry_Type">
		<xsd:annotation>
			<xsd:documentation>Definition of a code list entry.
        It consists of a code and its explanation.
        If the code represents a class of numerical values,
        its range is described by minInclusive/minExclusive and/or maxInclusive/maxExclusive.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Code" type="xsd:string"/>
			<xsd:element name="Explanation" type="xsd:string" minOccurs="0"/>
			<xsd:choice>
				<xsd:element name="minInclusive" type="sq:NumericType" minOccurs="0"/>
				<xsd:element name="minExclusive" type="sq:NumericType" minOccurs="0"/>
			</xsd:choice>
			<xsd:choice>
				<xsd:element name="maxInclusive" type="sq:NumericType" minOccurs="0"/>
				<xsd:element name="maxExclusive" type="sq:NumericType" minOccurs="0"/>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="NumericType">
		<xsd:union memberTypes="xsd:float xsd:decimal xsd:double"/>
	</xsd:simpleType>
</xsd:schema>

=== Ezio47/hale/hale/eu.esdihumboldt.hale.io.gml.test/src/data/buek200/target/buek200_propertyFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<SoilML_PropertyFile xmlns="http://www.SoilML.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.SoilML.org LATEST_SOILML/propertyFile.xsd" xmlns:sqdf="http://www.SoilML.org/dataFile" 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:gmd="http://www.isotc211.org/2005/gmd" 
xmlns:gco="http://www.isotc211.org/2005/gco" 
xmlns:gml="http://www.isotc211.org/2005/gml">
	<gmd:MD_Metadata>
		<gmd:contact>
			<gmd:CI_ResponsibleParty>
				<gmd:organisationName>
					<gco:CharacterString>Federal Institute of Geosciences and Natural Resources</gco:CharacterString>
				</gmd:organisationName>
				<gmd:contactInfo>
					<gmd:CI_Contact>
						<gmd:address>
							<gmd:CI_Address>
								<gmd:deliveryPoint>
									<gco:CharacterString>Stilleweg 2</gco:CharacterString>
								</gmd:deliveryPoint>
								<gmd:city>
									<gco:CharacterString>Hannover</gco:CharacterString>
								</gmd:city>
								<gmd:administrativeArea>
									<gco:CharacterString/>
								</gmd:administrativeArea>
								<gmd:postalCode>
									<gco:CharacterString>D-30655</gco:CharacterString>
								</gmd:postalCode>
								<gmd:country>
									<gco:CharacterString>Deutschland</gco:CharacterString>
								</gmd:country>
								<gmd:electronicMailAddress>
									<gco:CharacterString>poststelle@bgr.de</gco:CharacterString>
								</gmd:electronicMailAddress>
							</gmd:CI_Address>
						</gmd:address>
					</gmd:CI_Contact>
				</gmd:contactInfo>
				<gmd:role>
					<gmd:CI_RoleCode codeListValue="pointOfContact" codeList="http://www.isotc211.org/2005/resources/codeList.xml#CI_RoleCode">pointOfContact</gmd:CI_RoleCode>
				</gmd:role>
			</gmd:CI_ResponsibleParty>
		</gmd:contact>
		<gmd:dateStamp>
			<gco:Date>2010-11-08</gco:Date>
		</gmd:dateStamp>
		<gmd:identificationInfo>
			<gmd:MD_DataIdentification>
				<gmd:citation>
					<gmd:CI_Citation>
						<gmd:title>
							<gco:CharacterString>Bodenübersichtskarte 1:200.000</gco:CharacterString>
						</gmd:title>
						<gmd:date>
							<gmd:CI_Date>
								<gmd:date>
									<gco:Date>2010-11-08</gco:Date>
								</gmd:date>
								<gmd:dateType>
									<gmd:CI_DateTypeCode codeListValue="publication" codeList="http://www.isotc211.org/2005/resources/codeList.xml#CI_DateTypeCode">publication</gmd:CI_DateTypeCode>
								</gmd:dateType>
							</gmd:CI_Date>
						</gmd:date>
						<gmd:edition>
							<gco:CharacterString>2005</gco:CharacterString>
						</gmd:edition>
					</gmd:CI_Citation>
				</gmd:citation>
				<gmd:abstract>
					<gco:CharacterString>Soil map series at scale 1:200.000 covering Germany consisting of 55 sheets</gco:CharacterString>
				</gmd:abstract>
				<gmd:pointOfContact>
					<gmd:CI_ResponsibleParty>
						<gmd:organisationName>
							<gco:CharacterString>Federal Institute of Geoscience and Natural Resources</gco:CharacterString>
						</gmd:organisationName>
						<gmd:contactInfo>
							<gmd:CI_Contact>
								<gmd:address>
									<gmd:CI_Address>
										<gmd:deliveryPoint>
											<gco:CharacterString>Stilleweg 2</gco:CharacterString>
										</gmd:deliveryPoint>
										<gmd:city>
											<gco:CharacterString>Hannover</gco:CharacterString>
										</gmd:city>
										<gmd:administrativeArea>
											<gco:CharacterString/>
										</gmd:administrativeArea>
										<gmd:postalCode>
											<gco:CharacterString>D-30655</gco:CharacterString>
										</gmd:postalCode>
										<gmd:country>
											<gco:CharacterString>Deutschland</gco:CharacterString>
										</gmd:country>
										<gmd:electronicMailAddress>
											<gco:CharacterString>poststelle@bgr.de</gco:CharacterString>
										</gmd:electronicMailAddress>
									</gmd:CI_Address>
								</gmd:address>
							</gmd:CI_Contact>
						</gmd:contactInfo>
						<gmd:role>
							<gmd:CI_RoleCode codeList="http://www.isotc211.org/2005/resources/codeList.xml#CI_RoleCode" codeListValue="pointOfContact">pointOfContact</gmd:CI_RoleCode>
						</gmd:role>
					</gmd:CI_ResponsibleParty>
				</gmd:pointOfContact>
				<gmd:language>
					<gco:CharacterString>ger</gco:CharacterString>
				</gmd:language>
				<gmd:characterSet>
					<gmd:MD_CharacterSetCode codeListValue="utf8" codeList="http://www.isotc211.org/2005/resources/codeList.xml#MD_CharacterSetCode">utf8</gmd:MD_CharacterSetCode>
				</gmd:characterSet>
			</gmd:MD_DataIdentification>
		</gmd:identificationInfo>
	</gmd:MD_Metadata>
	
	<FeatureTypes>
		<FeatureType id="feature_1">
			<FeatureTypeName>Site</FeatureTypeName>
			<XSDTypeName>Buek200_Sheet</XSDTypeName>
			<Property id="f1.property_1">
				<PropertyName>Title</PropertyName>
				<Title>Title</Title>
				<Description>contains the name of the respective map sheet of the series</Description>
			</Property>
			<Property id="f1.property_2">
				<PropertyName>Number</PropertyName>
				<Title>Number</Title>
				<Description>contains the number of the respective map sheet of the series, e.g. CC7910</Description>
			</Property>
			
			
		</FeatureType>
		
		<FeatureType id="feature_2">
			<FeatureTypeName>Surface</FeatureTypeName>
			<XSDTypeName>Buek200_Sheet_Surface</XSDTypeName>
			<Property id="f2.property_1">
				<PropertyName>GE</PropertyName>
				<Description>Generallegendeneinheit, als Attribut zur Geometrie</Description>
			</Property>
			<Property id="f2.property_2">
				<PropertyName>LE</PropertyName>
				<Description>Legendeneinheit, als Attribut zur Geometrie und spezifisch für das Kartenblatt</Description>
			</Property>
			<Property id="f2.property_3">
				<PropertyName>concernedMapSheet</PropertyName>
				<Title>concernedMapSheet</Title>
				<Description>Holds the ID-Number of that map sheet to which geometry described in this section belongs</Description>
			</Property>
		</FeatureType>
		
	   <FeatureType id="feature_3">
					<FeatureTypeName>SoilMappingUnit</FeatureTypeName>
					<XSDTypeName>Buek200_SoilMappingUnit</XSDTypeName>
					<Property id="f3.property_1">
						<PropertyName>Generallegendeneinheit</PropertyName>
						<Description>Number that enables comparison of mapping units 
						between map sheets of a series. Numbering of units differs from map sheet to map sheet. 
						"Generallegendeneinheit" is similar to a look up table: General unit = unit number in sheet 1, unit number in sheet , ... but referring to one common mapping unit</Description>
					</Property>
					<Property id="f3.property_2">
						<PropertyName>Bodenlandschaft</PropertyName>
						<Description>Aggregation</Description>
					</Property>
					<Property id="f3.property_3">
						<PropertyName>Bodengroßlandschaft</PropertyName>
						<Description>Aggregation</Description>
					</Property>
					<Property id="f3.property_4">
						<PropertyName>Bodenregion</PropertyName>
						<Description>Aggregation</Description>
					</Property>
		</FeatureType>
		
		<FeatureType id="feature_4">
				  <FeatureTypeName>Horizon</FeatureTypeName>
					<XSDTypeName>GermanKA4Horizon</XSDTypeName>
			<Property id="f4.property_1">
			<PropertyName>CoarseFragments</PropertyName>
				<Description>Grobbodenanteilsklasse - coarse fragments content class - in Volumen-%</Description>
				<CodeList id="grobbodenListe">
					<CodeListEntry>
						<Code>1</Code>
						<Explanation>sehr schwach steinig, kiesig, grusig</Explanation>
						<maxExclusive>2</maxExclusive>
					</CodeListEntry>
					<CodeListEntry>
						<Code>2</Code>
						<Explanation>schwach steinig, kiesig, grusig</Explanation>
						<minInclusive>2</minInclusive>
						<maxExclusive>10</maxExclusive>
					</CodeListEntry>
					<CodeListEntry>
						<Code>3</Code>
						<Explanation>mittel steinig, kiesig, grusig</Explanation>
						<minInclusive>10</minInclusive>
						<maxExclusive>25</maxExclusive>
					</CodeListEntry>
					<CodeListEntry>
						<Code>4</Code>
						<Explanation>stark steinig, kiesig, grusig</Explanation>
						<minInclusive>25</minInclusive>
						<maxExclusive>50</maxExclusive>
					</CodeListEntry>
					<CodeListEntry>
						<Code>5</Code>
						<Explanation>sehr stark steinig, kiesig, grusig</Explanation>
						<minInclusive>50</minInclusive>
						<maxExclusive>75</maxExclusive>
					</CodeListEntry>
					<CodeListEntry>
						<Code>6</Code>
						<Explanation>Steine, Kies, Grus</Explanation>
						<minInclusive>75</minInclusive>
					</CodeListEntry>
				</CodeList>
			</Property>
			<Property id="f4.property_2">
				<PropertyName>Texture</PropertyName>
				<Description>Bodenart - Soil texture - in Masse-%</Description>
				<CodeList id="bodenartenListe">
					<CodeListEntry>
						<Code>Ss</Code>
						<Explanation>reiner Sand</Explanation>
					</CodeListEntry>
					<CodeListEntry>
						<Code>Su2</Code>
						<Explanation>schwach schluffiger Sand</Explanation>
					</CodeListEntry>
					<CodeListEntry>
						<Code>Sl2</Code>
						<Explanation>schwach lehmiger Sand</Explanation>
					</CodeListEntry>
					<CodeListEntry>
						<Code>Sl3</Code>
						<Explanation>mittel lehmiger Sand</Explanation>
					</CodeListEntry>
					<CodeListEntry>
						<Code>St2</Code>
						<Explanation>schwach toniger Sand</Explanation>
					</CodeListEntry>
					<CodeListEntry>
						<Code>Su3</Code>
						<Explanation>mittel schlufiger Sand</Explanation>
					</CodeListEntry>
					<CodeListEntry>
						<Code>Su4</Code>
						<Explanation>stark schluffigerSand</Explanation>
					</CodeListEntry>
					<CodeListEntry>
						<Code>Slu</Code>
						<Explanation>schluffig-lehmiger Sand</Explanation>
					</CodeListEntry>
					<CodeListEntry>
						<Code>Sl4</Code>
						<Explanation>stark lehmiger Sand</Explanation>
					</CodeListEntry>
					<CodeListEntry>
						<Code>St3</Code>
						<Explanation>mittel toniger Sand</Explanation>
					</CodeListEntry>
					<CodeListEntry>
						<Code>Ls2</Code>
						<Explanation>schwach sandiger Lehm</Explanation>
					</CodeListEntry>
				    <CodeListEntry>
						<Code>Ls3</Code>
